---
- hosts: "{{ hosts }}"
  become: yes
  gather_facts: no
  
  vars: 
    ## 全局设置，如果files变量未设置，则使用以下设置
    base_url: https://120.198.253.154:10443/api/v4/projects/
    branch: master
    token:
    owner: root
    group: root
    mode: '0640'
    force: no
    files:
#      - project_id:       ## 项目ID，可在gitlab项目设置中查看
#        branch: master    ## gitlab分支
#        file_path:        ## gitlab项目文件路径，路径分隔符需转换为 %2F
#        dest:             ## 文件保存路径（包含文件名）
#        token:            ## gitlab用户的private_token，需在用户设置中创建
#        owner:            ## 文件拥有者
#        group:            ## 文件属组
#        mode:             ## 文件权限
#        force:        ## 是否强制覆盖（yes/no）
  
  tasks:
    - name: Download file to remote host by a gitlab url
      get_url:
        url: "{{ base_url }}{{ item.project_id }}/repository/files/{{ item.file_path }}/raw?ref={{ item.branch if item.branch is defined and item.branch else branch }}"
        dest: "{{ item.dest }}"
        headers: "PRIVATE-TOKEN: {{ item.token if item.token else token }}"
        owner: "{{ item.owner if item.owner is defined and item.owner else owner }}"
        group: "{{ item.group if item.group is defined and item.group else group }}"
        mode: "{{ item.mode if item.mode is defined and item.mode else mode }}"
        force: "{{ item.force if item.force is defined and item.force else force }}"
        validate_certs: no
      with_items: "{{ files }}"
