---
- hosts: "{{ target }}"
  become: yes

  vars:
    script_get_url:
    script_args: 
    exec_user: root

  tasks:
    - name: Touch A Temp File
      command: mktemp -u
      register: temp_file

    - name: Download Script File
      get_url:
        url: "{{ script_get_url }}"
        dest: "{{ temp_file.stdout }}"
        mode: 0500
        owner: "{{ exec_user }}"

    - name: Exec Script On Remote Host
      shell: nohup {{ temp_file.stdout }} {{ script_args }}
      args:
        chdir: /tmp
      become_user: "{{ exec_user }}"
      ignore_errors: True

    - name: Remove temp Script File
      file: 
        dest: "{{ temp_file.stdout }}"
        state: absent
