---
- hosts: "{{ hosts }}"
  become: yes
  gather_facts: no
  
  vars: 
    owner: root
    group: root
    arch_type: module ## 打包方式（module/raw），module方式会忽略0字节的空文件

    unarch:
#      src:           ## 压缩包文件路径
#      dest:          ## 待解压目录
#      rm_path:       ## 需要事先删除的目录
#      create_path:   ## 需要创建的目录
#      owner:         ## 文件拥有者
#      group:         ## 文件属组
  
  tasks:
    - name: Remove "{{ unarch.rm_path }}"
      file:
        path: "{{ unarch.rm_path }}"
        state: absent
      when: unarch.rm_path is defined and unarch.rm_path

    - name: Create "{{ unarch.create_path }}"
      file:
        path: "{{ unarch.create_path }}"
        owner: "{{ unarch.owner if unarch.owner is defined and unarch.owner else owner }}"
        group: "{{ unarch.group if unarch.group is defined and unarch.owner else group }}"
        recurse: yes
        state: directory
      when: unarch.create_path is defined and unarch.create_path

    - name: Unarchive {{ unarch.src }} to {{ unarch.dest }}
      unarchive:
        src: "{{ unarch.src }}"
        dest: "{{ unarch.dest }}"
        owner: "{{ unarch.owner if unarch.owner is defined and unarch.owner else owner }}"
        group: "{{ unarch.group if unarch.group is defined and unarch.owner else group }}"
