---
- hosts: "{{ target }}"
  become: yes
  gather_facts: no 

  vars:
    version: 
    tomcat_user: tomcat
    tomcat_home:

    tomcat_http_port: 8080
    tomcat_https_port: 8443

    tomcat_exec_start: bin/startup.sh
    tomcat_exec_stop: bin/shutdown.sh

    # 可选是否安装java，默认安装
    java_install_flag: True
    tomcat_java_home:
    wars:
#      - name: s
#        get_url: http://172.16.100.191/docs/s.war

  tasks:
    - name: Undeploy War
      file:
        path: "{{ tomcat_home }}/webapps/{{ item[0].name + item[1] }}"
        state: absent
      with_nested:
        - "{{ wars }}"
        - ['.war', '']

    - name: Download War File
      get_url:
        url: "{{ item.get_url }}"
        dest: "{{ tomcat_home }}/webapps/{{ item.name }}.war"
        mode: 0644
      become: "{{ tomcat_user }}"
      with_items: "{{ wars }}"
      notify: restart tomcat
