---
- hosts: "{{ target }}"
  become: yes
  gather_facts: no 
#  vars:
#    target: test
#    wars:
#      - { 'name': 's', 'get_url': 'http://172.16.100.191/docs/s.war', 'version': 'v1.0' }

  tasks:
    - include_role:
        name: tomcat
        tasks_from: war
