---
- name: Exec Command {{ cmd.name }}
  shell: "{{ cmd.name }}"
  args:
    chdir: "{{ cmd.path if cmd.path is defined and cmd.path else None }}"
  become_user: "{{ cmd.owner if cmd.owner is defined and cmd.owner else owner }}"
