---
- include: "{{ task_file }}"
  vars:
    task_file: "{{ 'win_command.yml' if ansible_os_family == 'Windows' else 'command.yml' }}"
  become: "{{ 'no' if ansible_os_family == 'Windows' else 'yes' }}"
