---
- stat: 
    path: "{{ app_home }}"
  register: stat_app

- name: Stop {{ app_name }}
  shell: nohup {{ app_exec_stop }}
  become_user: "{{ app_user }}"
  args:
    chdir: "{{ app_home }}"
  when: stat_app.stat.isdir is defined and stat_app.stat.isdir

- name: Remove previous {{ app_home }}
  file:
    path: "{{ app_home }}-pre"
    state: absent

- name: Backup {{ app_home }}
  command: mv {{ app_home }} {{ app_home }}-pre
  args: 
    chdir: "{{ app_prefix }}"
  when: 
    - app_release_mode == 'full'
    - stat_app.stat.isdir is defined and stat_app.stat.isdir

- name: Backup {{ app_home }}
  command: cp -a {{ app_home }} {{ app_home }}-pre
  args: 
    chdir: "{{ app_prefix }}"
  when:
    - app_release_mode == 'delta'
    - stat_app.stat.isdir is defined and stat_app.stat.isdir

- name: Install {{ app_name }}
  unarchive:
    src: "{{ app_get_url }}"
    dest: "{{ app_prefix }}"
    owner: "{{ app_user }}"

- name: Run {{ app_name }}
  shell: nohup {{ app_exec_start }}
  become_user: "{{ app_user }}"
  args:
    chdir: "{{ app_home }}"
