tomcat_user: tomcat
tomcat_prefix: /opt
tomcat_version: 8
tomcat_home: >-
  {% if tomcat_version == 8 -%}
    {{ tomcat_prefix }}/apache-tomcat-8.0.43
  {%- elif tomcat_version == 7 -%}
    {{ tomcat_prefix }}/apache-tomcat-7.0.69
  {%- endif %}
tomcat_get_url: >-
  {% if tomcat_version == 8 -%}
    apache-tomcat-8.0.43.tar.gz
  {%- elif tomcat_version == 7 -%}
    apache-tomcat-7.0.69.tar.gz
  {%- endif %}

tomcat_http_port: 8080
tomcat_https_port: 8443

tomcat_admin_user: admin
tomcat_admin_pass: admin123!@#

# 过渡用，用于非Ansible安装的tomcat
tomcat_exec_flag: False
tomcat_exec_start: bin/startup.sh
tomcat_exec_stop: bin/shutdown.sh

# 可选是否安装java，默认安装
java_install_flag: True
java_home:
