tomcat_user: tomcat
tomcat_prefix: /usr/share
tomcat_version: 8
tomcat_home: >-
  {% if tomcat_version == 8 -%}
    {{ tomcat_prefix }}/apache-tomcat-8.0.43
  {%- elif tomcat_version == 7 -%}
    {{ tomcat_prefix }}/apache-tomcat-7.0.69
  {%- endif %}
tomcat_get_url: >-
  {% if tomcat_version == 8 -%}
    apache-tomcat-8.0.43.tar.gz
  {%- elif tomcat_version == 7 -%}
    apache-tomcat-7.0.69.tar.gz
  {%- endif %}

tomcat_http_port: 8080
tomcat_https_port: 8443

tomcat_admin_user: admin
tomcat_admin_pass: admin123!@#
