---
- name: Install JDK
  unarchive:
    src: "{{ java_get_url }}"
    dest: "{{ java_prefix }}"
    owner: root
    group: root
    creates: "{{ java_home }}"

- name: Link java to /usr/local/bin/
  file:
    src: "{{ java_home }}/bin/java"
    dest: /usr/local/bin/java
    mode: 0755
    owner: root
    group: root
    state: link
    force: yes
