---
- name: Undeploy War
  file:
    path: "{{ tomcat_home }}/webapps/{{ item[0].name + item[1] }}"
    state: absent
  with_nested:
    - "{{ wars }}"
    - ['.war', '']

- name: Download War File
  get_url:
    url: "{{ item.get_url }}"
    dest: "{{ tomcat_home }}/webapps/{{ item.name }}.war"
    mode: 0644
    force: yes
    backup: yes
  with_items: "{{ wars }}"
  notify: restart tomcat
