---
- name: Archive specified folder
  archive:
    path: "{{ arch.path }}"
    dest: "{{ arch.dest }}"
    owner: "{{ arch.owner if arch.owner is defined and arch.owner else owner }}"
    group: "{{ arch.group if arch.group is defined and arch.group else group }}"
